//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signup_with_login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web;

    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.orderts = new HashSet<ordert>();
        }
    
        public int Id { get; set; }

        [DisplayName("Movie Name")]
        [Required(ErrorMessage = "Movie Name is required")]
        public string name { get; set; }

        [DisplayName("Release Year")]
        [Required(ErrorMessage = "Release Year is required")]
        [Range(1900,2050,ErrorMessage ="Put a valid year")]
        public int realease_year { get; set; }

        [DisplayName("Enter Image")]
        [Required(ErrorMessage = "Image is required")]
        public string image_path { get; set; }

        [DisplayName("Price")]
        [Required(ErrorMessage = "Price is required")]
        [Range(100,600,ErrorMessage ="Invalid Price Entry")]
        public Nullable<int> price { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordert> orderts { get; set; }
    }
}
