//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signup_with_login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ordert
    {
        public int Id { get; set; }
        [DisplayName("Movie Id")]
        public Nullable<int> movie_id { get; set; }
        [DisplayName("Customer Id")]
        public Nullable<int> cust_id { get; set; }

        [DisplayName("Price")]
        public Nullable<int> price { get; set; }
        [DisplayName("Total Price")]
        public Nullable<int> total_price { get; set; }
        [DisplayName("Quantity")]
        public Nullable<int> quantity { get; set; }
        [DisplayName("Order Date")]
        public System.DateTime order_date { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual user user { get; set; }
    }
}
