//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signup_with_login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Role1 { get; set; }
    
        public virtual user user { get; set; }
    }
}
